parameters:
#    fiscalite_budget.example.class: Fiscalite\BudgetBundle\Example

services:
#    fiscalite_budget.example:
#        class: %fiscalite_budget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
