<?php

namespace BackOffice\MonitoringBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * CodeOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeOperationRepository extends EntityRepository
{
    public function search($datas, $sort = null, $isAdapter = false)
    {
        $query = $this
            ->createQueryBuilder('co')
            ->where('co.id IS NOT NULL');

        if (isset($datas['code']) && $datas['code'] != "") {
            $query
                ->andWhere('co.code = :c')
                ->setParameter('c', $datas['code']);
        }
        if (isset($datas['libelle']) && $datas['libelle']) {
            $query
                ->andWhere('co.libelle LIKE :l')
                ->setParameter('l', "%" . $datas['libelle'] . "%");
        }
        
        if ($sort) {
            $arraySort = explode('-', $sort);
            $query->orderBy('co.' . $arraySort[0], $arraySort[1]);
        } else {
            $query->orderBy('co.code', 'ASC');
        }

        if ($isAdapter) {
            return new DoctrineORMAdapter($query);
        } else {
            return $query->getQuery()->getResult();
        }
    }
}
