<?php

namespace BackOffice\MonitoringBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailRepository extends EntityRepository
{
    public function searchLast($action, $module, $id)
    {
        $query = $this
            ->createQueryBuilder('m')
            ->where('m.actionLog = :al')
            ->setParameter('al', $action)
            ->andWhere('m.moduleLog = :ml')
            ->setParameter('ml', $module)
            ->andWhere('m.isSended = FALSE')
            ->andWhere('m.id <> :mi')
            ->setParameter('mi', $id)
            ->orderBy('m.datetime', 'ASC');
        
        return $query->getQuery()->getResult();
    }
    
    public function lastSending($action, $module, $id)
    {
        $query = $this
            ->createQueryBuilder('m')
            ->select('MAX(m.datetime) AS lastSending')
            ->where('m.actionLog = :al')
            ->setParameter('al', $action)
            ->andWhere('m.moduleLog = :ml')
            ->setParameter('ml', $module)
            ->andWhere('m.isSended = 1')
            ->andWhere('m.id <> :mi')
            ->setParameter('mi', $id)
            ->orderBy('m.datetime', 'ASC');
        
        return $query->getQuery()->getOneOrNullResult();
    }
}
