<?php

namespace BackOffice\MonitoringBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PerformanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerformanceRepository extends EntityRepository
{
    public function findLast30()
    {
        $res = array();
        $lastDay = new \DateTime;
        $lastDay->modify('-30 day');

        $query = $this->createQueryBuilder('perf');
        $query
            ->andWhere($query->expr()->gte('perf.datetime', ':datetime'))
            ->setParameter('datetime', $lastDay)
            ->orderBy('perf.datetime', 'DESC')
            ->setMaxResults(30);

        $datas = $query->getQuery()->getResult();
        foreach ($datas as $r) {
            $res[date_format($r->getDateTime(), 'd/m/Y')]=$r;
        }

        return $res;
    }
}
