BackOffice\CustomerBundle\Entity\Customer:
    properties:
        siren:
            - Length :
                min: 9
                max: 9
                exactMessage: "Le Siren doit être de 9 caractères"
        codeNic:
            - Length :
                min: 5
                max: 5
                exactMessage: "Le Code Nic doit être de 5 caractères (type 000xx)"
        codePays:
            - Length :
                min: 1
                max: 3
        dateNaissance:
            - Date:
                message: "Cette valeur n'est pas un format de date valide"
        dateCreation:
            - Date:
                message: "Cette valeur n'est pas un format de date valide"
        email:
            - Email:
                message: "Ce n'est pas un format d'email correct"
        cP:
            - Length :
                min: 5
                max: 5
                exactMessage: "Le code postal doit être d'exactement 5 caractères"
        codeApe:
            - Length :
                min: 5
                max: 5
                exactMessage: "Le code Ape doit être d'exactement 5 caractères"
        coteActivite:
            - Length :
                min: 1
                max: 1
                exactMessage: "La cote activite doit être d'exactement 1 caractères"
        cotecredit:
            - Length :
                min: 3
                max: 3
                exactMessage: "La cote credit doit être d'exactement 3 caractères"