<?php

namespace Editique\TitreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use BackOffice\ParserBundle\Manager\ParserManager;

/**
 * AvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends EntityRepository
{
    public function findLast()
    {
        $jourVeille = strftime("%y", mktime(0, 0, 0, date('m'), date('d')-1, date('y')));
        
        $query = $this
                    ->createQueryBuilder('a')
                    ->where('a.jourCreation = ' . $jourVeille);

        return $query->getQuery()->getResult();
    }
}
