<?php

namespace BackOffice\CleanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegleNettoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegleNettoyageRepository extends EntityRepository
{
}
