services:
    editique.IFUManager:
        class: Editique\FiscalBundle\Manager\IFUManager
        calls:
            - [ setEcritureManager, [ @backoffice_parser.ecritureManager ] ]
            - [ setLectureManager, [ @backoffice_parser.lectureManager ] ]
            - [ setLogManager, [ @backoffice_monitoring.logManager ] ]
            - [ setEntityManager, [ @doctrine ] ]
            - [ setFileManager, [ @backoffice_file.fileManager ] ]     
            - [ setWindowsFTPManager, [ @back_office_connexion.windowsFTP ] ]          
            - [ setPDFManager, [ @ps_pdf.facade] ]
            - [ setTplManager, [ @templating] ]