parameters:
#    back_office_clean.example.class: BackOffice\CleanBundle\Example

services:
#    back_office_clean.example:
#        class: %back_office_clean.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
