<?php

namespace Fiscalite\ODBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CorrespondanceComptesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrespondanceComptesRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('numCompteInterne' => 'ASC'));
    }

    public function search($datas, $sort = null)
    {
        $query = $this
                    ->createQueryBuilder('c')
                    ->where('c.numCompteInterne IS NOT NULL');

        if (isset($datas['numCompteInterne']) && $datas['numCompteInterne'] != "") {
            $query
                ->andWhere('c.numCompteInterne LIKE :nci')
                ->setParameter('nci', "%".$datas['numCompteInterne']."%");
        }
        if (isset($datas['numCompteExterne']) && $datas['numCompteExterne'] != "") {
            $query
                ->andWhere('c.numCompteExterne LIKE :nce')
                ->setParameter('nce', "%".$datas['numCompteExterne']."%");
        }

        if ($sort) {
            $arraySort = explode('-', $sort);
            $query->orderBy('c.'.$arraySort[0], $arraySort[1]);
        } else {
            $query->orderBy('c.numCompteInterne', 'ASC');
        }

        return $query->getQuery()->getResult();
    }
}
