parameters:
#    back_office_evolution.example.class: BackOffice\EvolutionBundle\Example

services:
#    back_office_evolution.example:
#        class: %back_office_evolution.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
