parameters:
#    monetique_card.example.class: Monetique\CardBundle\Example

services:
#    monetique_card.example:
#        class: %monetique_card.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
