<?php

namespace Monetique\CardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * P30SRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class P30SRepository extends EntityRepository
{
    public function search($datas)
    {
        $query = $this
            ->createQueryBuilder('p')
            ->where('p.id IS NOT NULL');
        
        if (isset($datas['dateDu']) && $datas['dateDu']) {
            $dt = ParserManager::transformDate($datas['dateDu']);
            $query
                ->andWhere($query->expr()->gte('p.dateEnr', ':dateDu'))
                ->setParameter('dateDu', $dt, \Doctrine\DBAL\Types\Type::DATETIME);
        }
        if (isset($datas['dateAu']) && $datas['dateAu']) {
            $dt = ParserManager::transformDate($datas['dateAu'], false);
            $query
                ->andWhere($query->expr()->lte('p.dateEnr', ':dateAu'))
                ->setParameter('dateAu', $dt, \Doctrine\DBAL\Types\Type::DATETIME);
        }
        
        $query->orderBy('p.id', 'DESC');
        
        return $query->getQuery()->getResult();
    }
    
    public function getNumFile()
    {
        $query = $this->createQueryBuilder('p')
            ->select('COUNT(p)')
            ->getQuery()
            ->getSingleScalarResult();
        
        return $query + 1;
    }
}
