<?php

namespace Fiscalite\ODBundle\EntityBFI2;

use Doctrine\ORM\EntityRepository;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('num' => 'DESC'));
    }
}
