imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# on ecrase certain parametre pour les tests unitaires
parameters: 
    logBFI.enabled : true
    logBFI.mail.enabled : false
    fichierLocalTest: /home/FIDUCIAL/spool_fichiers/test/test.txt
    fichierLocalTestVide: /home/FIDUCIAL/spool_fichiers/test/vide.txt
    repLocalTest: /home/FIDUCIAL/spool_fichiers/test/