imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@BackOfficeParserBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        cre_generation: "%cre_generation_hour%:%cre_generation_minute%"
        environment: "%environment%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - FOSUserBundle
        - FrontOfficeMainBundle
        - BackOfficeMonitoringBundle
        - BackOfficeUserBundle
        - BackOfficeCleanBundle
        - BackOfficeEvolutionBundle
        - FiscaliteODBundle
        - FiscaliteEtatsBundle
        - FiscaliteBudgetBundle
        - EditiqueMasterBundle
        - EditiqueRIBBundle
        - EditiqueReleveBundle
        - EditiqueDATBundle
        - EditiqueLivretBundle
        - EditiqueCreditBundle
        - EditiqueCompteBundle
        - EditiqueLettreBundle
        - EditiqueTitreBundle
        - EditiqueFiscalBundle
        - MonetiqueCardBundle
        - BackOfficeHabilitationBundle
        - BackOfficeCustomerBundle
        - TransversePartenaireBundle
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: bfi # précise la connexion utilisée par défaut
        connections:
            bfi:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_bfi_name%
                service:  %database_service%
                user:     %database_bfi_user%
                password: %database_bfi_password%
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: bfi
        entity_managers:
            bfi:
                connection: bfi
                mappings:
                  FiscaliteODBundle : ~
                  FiscaliteBudgetBundle : ~
                  BackOfficeMonitoringBundle : ~
                  BackOfficeActionBundle : ~
                  BackOfficeCleanBundle : ~
                  BackOfficeEvolutionBundle : ~
                  EditiqueMasterBundle : ~
                  EditiqueRIBBundle : ~
                  BackOfficeUserBundle : ~
                  MonetiqueCardBundle : ~
                  BackOfficeHabilitationBundle : ~
                  BackOfficeCustomerBundle : ~
                  TransversePartenaireBundle : ~
            bfi2:
                connection: bfi
                mappings:
                  FiscaliteODBundle :
                    # you must specify the type
                    type:     "annotation"
                    # The directory for entity (relative to bundle path)
                    dir:      "EntityBFI2"
                    #the prefix
                    prefix:   "Fiscalite\ODBundle\EntityBFI2"
                  EditiqueMasterBundle : ~
                  EditiqueDATBundle : ~
                  EditiqueLivretBundle : ~
                  EditiqueTitreBundle : ~
                  EditiqueReleveBundle : ~
                  EditiqueCreditBundle : ~
                  EditiqueCompteBundle : ~
                  EditiqueLettreBundle : ~
                  EditiqueFiscalBundle : ~


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

services:
    listener:
        class: Doctrine\DBAL\Event\Listeners\OracleSessionInit
        tags:
            - { name: doctrine.event_listener, event: postConnect }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: BackOffice\UserBundle\Entity\Profil
    from_email:
        address:        noreply@banque-fiducial.fr
        sender_name:    Banque Fiducial
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template: BackOfficeUserBundle:Resetting:email.html.twig
