transverse_partenaire:
    resource: "@TransversePartenaireBundle/Resources/config/routing.yml"
    prefix:   /transverse

fiscalite_budget:
    resource: "@FiscaliteBudgetBundle/Resources/config/routing.yml"
    prefix:   /

back_office_evolution:
    resource: "@BackOfficeEvolutionBundle/Resources/config/routing.yml"
    prefix:   /

monetique_card:
    resource: "@MonetiqueCardBundle/Resources/config/routing.yml"
    prefix:   /

editique_master:
    resource: "@EditiqueMasterBundle/Resources/config/routing.yml"
    prefix:   /

front_office_main:
    resource: "@FrontOfficeMainBundle/Resources/config/routing.yml"
    prefix:   /

fiscalite_od:
    resource: "@FiscaliteODBundle/Resources/config/routing.yml"
    prefix:   /fiscalite/od
    
fiscalite_etats:
    resource: "@FiscaliteEtatsBundle/Resources/config/routing.yml"
    prefix:   /fiscalite/etats-reglementaires

backoffice:
    resource: "@BackOfficeMonitoringBundle/Resources/config/routing.yml"
    prefix:   /backoffice

backoffice_clean:
    resource: "@BackOfficeCleanBundle/Resources/config/routing.yml"
    prefix:   /backoffice/clean

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
