services:
    editique.compteManager:
        class: Editique\CompteBundle\Manager\CompteManager
        calls:
            - [ setEcritureManager, [ @backoffice_parser.ecritureManager ] ]
            - [ setLectureManager, [ @backoffice_parser.lectureManager ] ]
            - [ setLogManager, [ @backoffice_monitoring.logManager ] ]
            - [ setEntityManager, [ @doctrine ] ]
            - [ setFileManager, [ @backoffice_file.fileManager ] ]
            - [ setWindowsFTPManager, [ @back_office_connexion.windowsFTP ] ]
            #- [ setAngersFTPManager, [ @back_office_connexion.angersFTP ] ]
            - [ setPDFManager, [ @ps_pdf.facade] ]
            - [ setTplManager, [ @templating] ]
        