<?php

namespace Editique\MasterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CorrespondanceReleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrespondanceReleveRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('libelle' => 'ASC'));
    }

    public function search($datas, $sort = null)
    {
        $query = $this
                    ->createQueryBuilder('c')
                    ->where('c.libelle IS NOT NULL');

        if (isset($datas['libelle']) && $datas['libelle'] != "") {
            $query
                ->andWhere('c.libelle LIKE :l')
                ->setParameter('l', "%".$datas['libelle']."%");
        }
        if (isset($datas['type']) && $datas['type'] != "") {
            $query
                ->andWhere('c.type LIKE :t')
                ->setParameter('t', "%".$datas['type']."%");
        }

        if ($sort) {
            $arraySort = explode('-', $sort);
            $query->orderBy('c.'.$arraySort[0], $arraySort[1]);
        } else {
            $query->orderBy('c.libelle', 'ASC');
        }

        return $query->getQuery()->getResult();
    }
}
