<?php

namespace Editique\MasterBundle\Entity;

use Doctrine\ORM\EntityRepository;
use BackOffice\ParserBundle\Manager\ParserManager;

/**
 * EditiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditiqueRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('dtGeneration' => 'DESC'));
    }

    public function getDoc($idClient, $numCpt)
    {
        $query = $this
            ->createQueryBuilder('e')
            ->where('e.idClient = :idClient')
            ->orWhere('e.numCpt = :numCpt')
            ->setParameters(array('idClient' => $idClient, 'numCpt' => $numCpt));

        return $query->getQuery()->getResult();
    }

    public function search($datas, $sort = null)
    {
        $query = $this
            ->createQueryBuilder('e')
            ->where('e.id IS NOT NULL');

        if (isset($datas['idClient']) && $datas['idClient'] != "") {
            $query
                ->andWhere('e.idClient LIKE :ic')
                ->setParameter('ic', "%".$datas['idClient']."%");
        }
        if (isset($datas['numCpt']) && $datas['numCpt']) {
            $query
                ->andWhere('e.numCpt LIKE :nc')
                ->setParameter('nc', "%".$datas['numCpt']."%");
        }
        if (isset($datas['typeDoc']) && $datas['typeDoc']) {
            $query
                ->andWhere('e.typeDoc = :td')
                ->setParameter('td', $datas['typeDoc']);
        }
        if (isset($datas['filePath']) && $datas['filePath']) {
            $query
                ->andWhere('e.filePath LIKE :fp')
                ->setParameter('fp', "%".$datas['filePath']."%");
        }
        if (isset($datas['dateDu']) && $datas['dateDu']) {
            $dt = ParserManager::transformDate($datas['dateDu']);
            $query
                ->andWhere($query->expr()->gte('e.dtGeneration', ':dateDu'))
                ->setParameter('dateDu', $dt, \Doctrine\DBAL\Types\Type::DATETIME);
        }
        if (isset($datas['dateAu']) && $datas['dateAu']) {
            $dt = ParserManager::transformDate($datas['dateAu'], false);
            $query
                ->andWhere($query->expr()->lte('e.dtGeneration', ':dateAu'))
                ->setParameter('dateAu', $dt, \Doctrine\DBAL\Types\Type::DATETIME);
        }
        if (isset($datas['idUtilisateur']) && $datas['idUtilisateur']) {
            $query
                ->andWhere('e.idUtilisateur = :iu')
                ->setParameter('iu', "%".$datas['idUtilisateur']."%");
        }

        if ($sort) {
            $arraySort = explode('-', $sort);
            $query->orderBy('e.'.$arraySort[0], $arraySort[1]);
        } else {
            $query->orderBy('e.dtGeneration', 'DESC');
        }

        return $query->getQuery()->getResult();
    }
    
    public function getAllFirme($idTiers)
    {
        $query = $this
            ->createQueryBuilder('e')
            ->where('e.id IS NOT NULL')
            ->andWhere("e.typeDoc = 'releve_quotidien'");
        
        $condition = "";
        $iterator = 1;
        foreach ($idTiers as $tiers) {
            if ($iterator != 1) {
                $condition .= 'OR ';
            }
            
            $condition .= "e.idClient LIKE '%" . $tiers . "%' ";
            
            $iterator++;
        }
        
        $query
            ->andWhere($condition)
            ->orderBy('e.dtGeneration', 'DESC');
        
        return $query->getQuery()->getResult();
    }
}
