<?php

namespace Editique\MasterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SouscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscriptionRepository extends EntityRepository
{
    
}
