<?php

namespace Editique\MasterBundle\Entity;

use Doctrine\ORM\EntityRepository;
use BackOffice\ParserBundle\Manager\ParserManager;

/**
 * TauxCreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TauxCreditRepository extends EntityRepository
{
    public function search($datas)
    {
        $query = $this
            ->createQueryBuilder('t')
            ->where('t.id IS NOT NULL');
        
        if (isset($datas['dateValDu']) && $datas['dateValDu']) {
            $dt = ParserManager::transformDate($datas['dateValDu']);
            $query
                ->andWhere($query->expr()->gte('t.dateVal', ':dateDu'))
                ->setParameter('dateDu', $dt, \Doctrine\DBAL\Types\Type::DATETIME);
        }
        if (isset($datas['dateValAu']) && $datas['dateValAu']) {
            $dt = ParserManager::transformDate($datas['dateValAu'], false);
            $query
                ->andWhere($query->expr()->lte('t.dateVal', ':dateAu'))
                ->setParameter('dateAu', $dt, \Doctrine\DBAL\Types\Type::DATETIME);
        }
        
        $query->orderBy('t.id', 'DESC');
        
        return $query->getQuery()->getResult();
    }
}
